//
//  MenuModel.swift
//  SMK.
//
//  Created by Harrinandhaan Sathish Kumaar Nirmala on 4/20/21.
//

import SwiftUI

// MARK: - MENU DATA MODEL

struct Menu: Identifiable, Hashable {
    var id = UUID()
    var title: String
    var headline: String
    var image: String
    var gradientColors: [Color]
    var description: String
    var nutrition: String
    var price: String
    var category: String
}


// MARK: - MENU DATA
let menuData: [Menu] = [
    Menu(  title:"Chapathi",
           headline:"An Indian bread served fresh from the tawa.",
           image:"Chapathi",
           gradientColors: [Color("Brown"), Color("Red3")],
           description:"Chapathi is a type of roti bread that is served all around the world.It is made of of wheat flour, oil, and water. Rolled and placed on a tawa.",
           nutrition: "104 Calories",
           price: "$2.99",
           category: "Vegetarian"),
    Menu(  title:"Parotta",
           headline:"A South Indian bread flaky with layers.",
           image:"parotta",
           gradientColors: [Color("Brown"), Color("Red3")],
           description:"Parotta is a flaky bread that is made from high precision skill. Rolled and placed on a flat pan and layered parrota ready!",
           nutrition: "274 Calories",
           price: "$2.99",
           category: "Vegetarian"),
    Menu(  title:"Naan",
           headline:"The greatest North Indian flatbread ever.",
           image:"garlicnaan",
           gradientColors: [Color("Brown"), Color("Red3")],
           description:"Naan is a tandoori food in India, mainly in the northern parts of it. Naan is served in 3 flavors, Tandoori, Garlic, or Butter.",
           nutrition: "93 Calories",
           price: "$3.99",
           category: "Vegetarian"),
    Menu(title:"Methi Paratha",
         headline: "A spicy North Indian bread made with fenugreek leaves.",
         image:"Methi-Paratha-3",
         gradientColors: [Color("Brown"), Color("Red3")],
         description:"Methi Paratha is a healthy type of flaky bread that is made of fenugreek and spices. It is very healthy, and is served with Masala Curd and Lettuce.",
         nutrition: "159 Calories",
         price: "$3.59",
         category: "Vegetarian"),
    Menu(title:"Aloo Paratha",
         headline: "A spicy potato filled bread served.",
         image:"AlooParatha",
         gradientColors: [Color("Brown"), Color("Red3")],
         description:"Aloo Paratha is a stuffed paratha made with cumin and potatoes. It is very healthy in nutrients, and is served with Masala Curd and Lettuce.",
         nutrition: "177 Calories",
         price: "$3.59",
         category: "Vegetarian"),
    Menu(title: "Idli",
         headline: "One of the world’s healthiest foods to eat.",
         image:"Idli",
         gradientColors: [Color("Blue2"), Color("Red2")],
         description:"Idli is one of the worlds healthiest foods to eat. It is a steamed lentil cake, with softness and fluffiness than a pillow. It is served with coconut chutney.",
         nutrition: "39 Calories",
         price: "$2.59",
         category: "Vegetarian"),
    Menu(title: "Paniyaram",
         headline: "A bite sized breakfast for yours truly.",
         image:"Paniyaram",
         gradientColors: [Color("Blue2"), Color("Red2")],
         description:"A snack to a dinner, Paniyaram is great for everyone. It is made out of lentils, and crispy on the outside with fluffiness on the inside. Served with coconut chutney.",
         nutrition: "278 Calories",
         price: "$2.49",
         category: "Vegetarian"),
    Menu(title: "Pongal",
          headline: "A delicacy made with ghee in South India.",
          image:"Pongal",
          gradientColors: [Color("Blue2"), Color("Red2")],
          description:"Pongal is a great way to start your day. The presence of ghee and curry leaves make it so scrumptious. Great taste with cashews as well. Served with coconut chutney.",
          nutrition: "212 Calories",
          price: "$3.49",
          category: "Vegetarian"),
    Menu(title:  "Vegetable Rava Kichidi",
         headline: "A type of meal to dig straight in.",
         image:"Kichidi",
         gradientColors: [Color("Blue2"), Color("Red2")],
         description:"A rava deliciousness. Filled with carrots, beans, and many more. Just a hint of ghee will make your day. Served with coconut chutney.",
         nutrition: "168 Calories",
         price: "$4.49",
         category: "Vegetarian"),
    Menu(title:  "Tomato Idiyappam",
         headline: "Steamed lentil noodles cover with masala",
         image:"tomato",
         gradientColors: [Color("Blue2"), Color("Red2")],
         description:"A common delicacy found in South India, and is prepared fresh in-house. With lentil noodles being tossed with masala, onions, and tomatoes, this will surely make a difference in your day.",
         nutrition: "468 Calories",
         price: "$4.99",
         category: "Vegetarian"),
    Menu(title:"Methi Corn Pulav",
          headline: "An alternate to biriyani, with fenugreek and corn.",
          image:"MethiPulav",
          gradientColors: [Color("Red"), Color("NeonPink")],
          description:"A veg masala rice. Made with corn and methi. With the aroma of basmati rice and fresh masala. Served with onions and raita.",
          nutrition: "226 Calories",
          price: "$6.59",
          category: "Vegetarian"),
    Menu(title:"Vegetable Biryani",
         headline: "An option for vegetarians, who devour masala.",
         image:"VegBiriyani",
         gradientColors: [Color("Red"), Color("NeonPink")],
         description:"A savory lunch, filled with steamed carrots, beans, and cauliflower. With the aroma of a traditional seeraga samba rice, this biriyani boasts due to it's in-house masala. This is served with raita and kurma.",
         nutrition: "241 Calories",
         price: "$7.99",
         category: "Vegetarian"),
    Menu(title:"Curd Rice",
         headline: "Give yourself a cool day.",
         image:"curdrice",
         gradientColors: [Color("Red"), Color("NeonPink")],
         description:"A cooler and refrsher to your hot sunny day. Rice mixed with in-house homemade curd, this will be devouring and scrumptious.",
         nutrition: "312 Calories",
         price: "$4.99",
         category: "Vegetarian"),
    Menu(title:"Chicken Fried Rice",
         headline: "Bring out the inner chinese foodie.",
         image:"chkrice",
         gradientColors: [Color("Red"), Color("NeonPink")],
         description:"A soaked and boiled basmati rice tossed with vegetables, grilled chicken and spring onions. Mized with our in house smoky schezwan sauce. Sauteed with roasted garlic and ginger to make one big flavorful explosion in your mouth.",
         nutrition: "329 Calories",
         price: "$5.49",
         category: "Non - Vegetarian"),
    Menu(title:"Chicken Biryani",
         headline: "Straight from the rice to chicken, all natural.",
         image:"chkbiriyani",
         gradientColors: [Color("Red"), Color("NeonPink")],
         description:"This yummy biriyani is made up of organic chicken, and filled with the most aromatic biryani rice ever, seeraga samba. With our in house masala, this day just gets better and is served with raita and kurma.",
         nutrition: "290 Calories",
         price: "$8.99",
         category: "Non - Vegetarian"),
    Menu(title:"Chilli Paneer",
         headline: "A great option for cheese lovers.",
         image:"chilpaneer",
         gradientColors: [Color("Szch"), Color("Spr")],
         description:"Cottage cheese marinated in curd and fried, with sautted vegetables, this makes the perfect starter for vegetarians and non - vegetarians. Served with mint chutney and avocado dip.",
         nutrition: "185 Calories",
         price: "$4.99",
         category: "Vegetarian"),
    Menu(title:"Cauliflower 65",
         headline: "An option for both veg and non veg lovers.",
         image:"gobi65",
         gradientColors: [Color("Szch"), Color("Spr")],
         description:"Cauliflower steamed and cooled, and then dipped in batter as fried in peanut oil. This crispy starter will leave the plate finished, and is served with mint chutney and avocado dip.",
         nutrition: "290 Calories",
         price: "$4.59",
         category: "Vegetarian"),
    Menu(title:"Red Chicken Fry",
         headline: "A sauteed chicken with endless taste.",
         image:"redchk",
         gradientColors: [Color("Szch"), Color("Spr")],
         description:"Chicken cut into bite sized pieces and then marinated in spices and curd. Then pan seared to make it taste and feel elegant. Served with mint chutney and avocado dip.",
         nutrition: "314 Calories",
         price: "$5.49",
         category: "Non - Vegetarian"),
    Menu(title:"Egg Kurma",
         headline: "A medium option for tasty gravy.",
         image:"eggkurma",
         gradientColors: [Color("Orange"), Color("Yellow")],
         description:"Slit eggs boiled and mixed with gravy. Made up of spices and coconut. Great for both rice and chapathi.",
         nutrition: "156 Calories",
         price: "$6.49",
         category: "Non - Vegetarian"),
    Menu(title:"Chicken Kheema",
         headline: "Minced chicken made into a delicacy.",
         image:"chkkhema",
         gradientColors: [Color("Orange"), Color("Yellow")],
         description:"Chicken minced and made into a curry with great flavored curry leaves. Eat with anything of your choice.",
         nutrition: "220 Calories",
         price: "$7.49",
         category: "Non - Vegetarian"),
    Menu(title:"Sambar",
         headline: "A dal to Idli and Pongal, with vegetables.",
         image:"sambar",
         gradientColors: [Color("Orange"), Color("Yellow")],
         description:"A great South Indian way to start your day. Dal boiled with drumsticks and onions. A great taste with many dishes.",
         nutrition: "139 Calories",
         price: "$3.99",
         category: "Vegetarian"),
    Menu(title:"Paneer Butter Masala",
         headline: "A side to Chapathi, and literally greatness.",
         image:"paneermasala",
         gradientColors: [Color("Orange"), Color("Yellow")],
         description:"Cottage cheese gravy with methi and all creamy deliciousness. The best gravy to eat with any flaky bread.",
         nutrition: "635 Calories",
         price: "$4.49",
         category: "Vegetarian"),
    Menu(title:"Chicken Kothu Parotta",
         headline: "Minced chicken + gravy + parotta = BOOM.",
         image:"chkkothu",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Minced and chopped chicken mized with our in house chicken kulambu and chopped up parotta. Served with chicken kurma and raita.",
         nutrition: "630 Calories",
         price: "$5.99",
         category: "Non - Vegetarian"),
    Menu(title:"Mutton Chops",
         headline: "Chops are better than your local iHops.",
         image:"muttonchops",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Organic mutton being cooked in a pool of onions, tomatoes, and our in - house spices. A perfect gravy to chapathi.",
         nutrition: "131 Calories",
         price: "$6.59",
         category: "Non - Vegetarian"),
    Menu(title:"Fish Fry",
         headline: "Fresh kingfish fry to your heart.",
         image:"fishfry",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Fresh kingfish from the market marinated with spices and sun - dried. Then oil fried or tawa fried.",
         nutrition: "240 Calories",
         price: "$6.99",
         category: "Seafood"),
    Menu(title:"Quail Masala",
         headline: "Fresh Quail mixed with onions and masala.",
         image:"quailmasala",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Fresh quail prepared with our in house masala, and mixed with onions, tomatoes, and coriander to create a bomb of flavor. Perfect for both chapathi and rice.",
         nutrition: "298.5 Calories",
         price: "$8.99",
         category: "Non - Vegetarian"),
    Menu(title:"Quail Fry",
         headline: "Oil fried quail with masala.",
         image:"quailfry",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Marinated quail set to dry out in the sun, then fried in peanut oil.",
         nutrition: "230 Calories",
         price: "$8.99",
         category: "Non - Vegetarian"),
    Menu(title:"Anchovy Fry",
         headline: "Small as a finger, tastes way better.",
         image:"nethilifry",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Fresh anchovies marinated with our in house spices, sun - dried, and fried in peanut oil. Served with mayonnaise.",
         nutrition: "70 Calories",
         price: "$8.59",
         category: "Seafood"),
    Menu(title:"Tomato Chutney",
         headline: "Mixed with tomato and spices to create a masterpiece.",
         image:"tomatochutney",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"A side to almost all South Indian breakfast items.",
         nutrition: "31 Calories",
         price: "$1.49",
         category: "Vegetarian"),
    Menu(title:"Coconut Chutney",
         headline: "Fresh coconut grinded with exotic spices like first class.",
         image:"coconutchutney",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Nice and fresh, with suitable to all items.",
         nutrition: "36 Calories",
         price: "$1.49",
         category: "Vegetarian"),
    Menu(title:"Mint Chutney",
         headline: "Mint from the garden turned into a wonderful piece of art.",
         image:"mintchutney",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Garden mint chutney great with Idli and other items.",
         nutrition: "10 Calories",
         price: "$1.49",
         category: "Vegetarian"),
    Menu(title:"Idli Podi - Gunpowder",
         headline: "Red chilies and grains mixed and grinded to create a soft powder.",
         image:"gunpowder",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Served with a choice of groundnut(peanut) oil or gingelly oil.",
         nutrition: "34 Calories",
         price: "$1.49",
         category: "Vegetarian"),
    Menu(title:"Avocado Dip",
         headline: "Ripe mexican avocados with curd to make a creamy dip.",
         image:"avocado",
         gradientColors: [Color("Dinner2"), Color("Dinner1")],
         description:"Avocados and curd mixed with salt, pepper, onion and tomatoes. Perfect for any starter.",
         nutrition: "34 Calories",
         price: "$1.49",
         category: "Vegetarian"),
    Menu(title:"Gulab Jamun",
         headline: "Fried dough balls soaked in sugar syrup.",
         image:"gj",
         gradientColors: [Color("Blue"), Color("Purple")],
         description:"Fried flour balls soaked in warm sugar syrup. A common delicacy found in India. Topped with pistachios and saffron.",
         nutrition: "112 Calories",
         price: "$2.49",
         category: "Vegetarian"),
    Menu(title:"Jalebi",
         headline: "A North Indian sweet found fresh at any stall.",
         image:"ji",
         gradientColors: [Color("Blue"), Color("Purple")],
         description:"An epic sweet found in almost every street of India. Juicy and hot, this will make you lick your fingers one by one. Fried mixture soaked in hot sugar syrup, just for you.",
         nutrition: "44 Calories",
         price: "$2.49",
         category: "Vegetarian"),
    Menu(title:"Rose Milk",
         headline: "Beat the heat with Rose Milk",
         image:"rose",
         gradientColors: [Color("Blue"), Color("Purple")],
         description:"An cooled drink made from real rose eccence, mixed with milk. To keep you fresh all day long.",
         nutrition: "315 Calories",
         price: "$1.49",
         category: "Vegetarian"),
    Menu(title:"Mango Lassi",
         headline: "The ones who drink are cool.",
         image:"mango",
         gradientColors: [Color("Blue"), Color("Purple")],
         description:"A fresh, ripe mango peeled and blended with cardamom and curd to make a thick beverage which will last one minute.",
         nutrition: "211 Calories",
         price: "$1.99",
         category: "Vegetarian"),
    Menu(title:"Aam Paana",
         headline: "A minty mangoey drink.",
         image:"aam",
         gradientColors: [Color("Blue"), Color("Purple")],
         description:"A North Indian delicacy that is pure of taste and minty fresh. Served fresh and cooled.",
         nutrition: "93 Calories",
         price: "$1.49",
         category: "Vegetarian"),
    Menu(title:"Lemon Juice",
         headline: "When life gives you lemons, make lemon juice.",
         image:"lemon",
         gradientColors: [Color("Blue"), Color("Purple")],
         description:"A tangy beverage for a perfect summer day. From the lemon to the sugar, it's all organic. Available either sweet or salty.",
         nutrition: "99 Calories",
         price: "$1.29",
         category: "Vegetarian"),
    
]

